# Generated by Django 5.1.9 on 2025-05-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Promo name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('promo_type', models.CharField(choices=[('percent', 'Percentage discount'), ('n_for_m', 'Buy N — Pay for M'), ('fixed_price', 'Fixed price for product set')], default='percent', max_length=20, verbose_name='Promo type')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, help_text='E.g., 10 for 10% off', max_digits=5, null=True, verbose_name='Discount (%)')),
                ('n', models.PositiveIntegerField(blank=True, null=True, verbose_name='Buy N')),
                ('m', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pay for M')),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fixed price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('products', models.ManyToManyField(related_name='promos', to='catalog.product', verbose_name='Products in promo')),
            ],
            options={
                'verbose_name': 'Promo',
                'verbose_name_plural': 'Promos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FixedPricePromo',
            fields=[
            ],
            options={
                'verbose_name': 'Fixed Price Promo',
                'verbose_name_plural': 'Fixed Price Promos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('promo.promo',),
        ),
        migrations.CreateModel(
            name='NForMPromo',
            fields=[
            ],
            options={
                'verbose_name': 'N-for-M Promo',
                'verbose_name_plural': 'N-for-M Promos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('promo.promo',),
        ),
        migrations.CreateModel(
            name='PercentPromo',
            fields=[
            ],
            options={
                'verbose_name': 'Percent Promo',
                'verbose_name_plural': 'Percent Promos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('promo.promo',),
        ),
        migrations.AddIndex(
            model_name='promo',
            index=models.Index(fields=['is_active', 'start_date', 'end_date'], name='promo_promo_is_acti_da2fe6_idx'),
        ),
    ]
