# Generated by Django 5.1.9 on 2025-05-26 15:33

from django.db import migrations, models


def add_debug_notes(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    for order in Order.objects.all():
        order.debug_note = f"Auto debug note for order #{order.id}"
        order.save(update_fields=['debug_note'])


def remove_debug_notes(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    for order in Order.objects.all():
        order.debug_note = ''
        order.save(update_fields=['debug_note'])


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0003_orderitem_promo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='debug_note',
            field=models.TextField(blank=True, verbose_name='Debug Note'),
        ),
        migrations.RunPython(add_debug_notes, remove_debug_notes),
    ]
