# Generated by Django 5.1.9 on 2025-05-26 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_debug_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='debug_note',
        ),
    ]
